// Code generated by kube-linter template codegen. DO NOT EDIT.
//go:build !templatecodegen
// +build !templatecodegen

package params

import (
	"fmt"
	"strings"

	"golang.stackrox.io/kube-linter/pkg/check"
	"golang.stackrox.io/kube-linter/pkg/templates/util"
)

var (
	// Use some imports in case they don't get used otherwise.
	_ = util.MustParseParameterDesc

	schemaLocationsParamDesc = util.MustParseParameterDesc(`{
	"Name": "schemaLocations",
	"Type": "array",
	"Description": "SchemaLocations contains locations of schemas to use. See: https://github.com/yannh/kubeconform/tree/master?tab=readme-ov-file#overriding-schemas-location",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "string",
	"Required": false,
	"NoRegex": true,
	"NotNegatable": false,
	"XXXStructFieldName": "SchemaLocations",
	"XXXIsPointer": false
}
`)

	cacheParamDesc = util.MustParseParameterDesc(`{
	"Name": "cache",
	"Type": "string",
	"Description": "Cache specifies the folder to cache schemas downloaded via HTTP.",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "",
	"Required": false,
	"NoRegex": true,
	"NotNegatable": false,
	"XXXStructFieldName": "Cache",
	"XXXIsPointer": false
}
`)

	skipKindsParamDesc = util.MustParseParameterDesc(`{
	"Name": "skipKinds",
	"Type": "array",
	"Description": "SkipKinds lists resource kinds to ignore during validation.",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "string",
	"Required": false,
	"NoRegex": true,
	"NotNegatable": false,
	"XXXStructFieldName": "SkipKinds",
	"XXXIsPointer": false
}
`)

	rejectKindsParamDesc = util.MustParseParameterDesc(`{
	"Name": "rejectKinds",
	"Type": "array",
	"Description": "RejectKinds lists resource kinds to reject during validation.",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "string",
	"Required": false,
	"NoRegex": true,
	"NotNegatable": false,
	"XXXStructFieldName": "RejectKinds",
	"XXXIsPointer": false
}
`)

	kubernetesVersionParamDesc = util.MustParseParameterDesc(`{
	"Name": "kubernetesVersion",
	"Type": "string",
	"Description": "KubernetesVersion specifies the Kubernetes version - must match one in https://github.com/instrumenta/kubernetes-json-schema",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "",
	"Required": false,
	"NoRegex": true,
	"NotNegatable": false,
	"XXXStructFieldName": "KubernetesVersion",
	"XXXIsPointer": false
}
`)

	strictParamDesc = util.MustParseParameterDesc(`{
	"Name": "strict",
	"Type": "boolean",
	"Description": "Strict enables strict validation that will error if resources contain undocumented fields.",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "Strict",
	"XXXIsPointer": false
}
`)

	ignoreMissingSchemasParamDesc = util.MustParseParameterDesc(`{
	"Name": "ignoreMissingSchemas",
	"Type": "boolean",
	"Description": "IgnoreMissingSchemas will skip validation for resources if no schema can be found.",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "IgnoreMissingSchemas",
	"XXXIsPointer": false
}
`)

	ParamDescs = []check.ParameterDesc{
		schemaLocationsParamDesc,
		cacheParamDesc,
		skipKindsParamDesc,
		rejectKindsParamDesc,
		kubernetesVersionParamDesc,
		strictParamDesc,
		ignoreMissingSchemasParamDesc,
	}
)

func (p *Params) Validate() error {
	var validationErrors []string
	if len(validationErrors) > 0 {
		return fmt.Errorf("invalid parameters: %s", strings.Join(validationErrors, ", "))
    }
	return nil
}

// ParseAndValidate instantiates a Params object out of the passed map[string]interface{},
// validates it, and returns it.
// The return type is interface{} to satisfy the type in the Template struct.
func ParseAndValidate(m map[string]interface{}) (interface{}, error) {
	var p Params
	if err := util.DecodeMapStructure(m, &p); err != nil {
		return nil, err
	}
	if err := p.Validate(); err != nil {
		return nil, err
	}
	return p, nil
}

// WrapInstantiateFunc is a convenience wrapper that wraps an untyped instantiate function
// into a typed one.
func WrapInstantiateFunc(f func(p Params) (check.Func, error)) func(interface{}) (check.Func, error) {
	return func(paramsInt interface{}) (check.Func, error) {
		return f(paramsInt.(Params))
	}
}
