changelog:
  categories:
    - title: "✔️ New checks"
      labels:
        - "new-check"
    - title: "🚀 Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bugfix"
        - "bug"
    - title: "🧰 Maintenance"
      labels:
        - "chore"
    - title: Other Changes
      labels:
        - '*'
    - title: '⬆️ Dependencies'
      labels:
        - 'dependencies'
