run:
  timeout: 5m

issues:
  exclude-use-default: false

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - Print
          - Printf
          - Println
          - Debug
          - Debugf
          - Info
          - Infof
          - Warn
          - Warnf
          - Error
          - Errorf
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - commentFormatting
      - octalLiteral
      - unnamedResult
      - unnecessaryDefer
      - importShadow
      - emptyStringTest
      - hugeParam
      - rangeValCopy
  gosec:
    excludes:
      - G101
  gosimple:
    go: "1.16"
    checks: ["all"]
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  revive:
    min-confidence: 0
    # Due to https://github.com/golangci/golangci-lint/issues/2355 on MacOS the linter is failing with the error
    # message too many files. Set the max-open-files explicitly.
    max-open-files: 2048
  staticcheck:
    go: "1.16"
    checks: ["all"]
  stylecheck:
    go: "1.16"
    checks: ["all", "-ST1000"]

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    # - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    - exportloopref
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    - gofmt
    - goimports
    # - gomnd
    # - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    - nakedret
    # - nestif
    - nolintlint
    # - prealloc
    - revive
    - rowserrcheck
    # - scopelint
    - staticcheck
    # - structcheck
    - stylecheck
    # - testpackage
    # - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck
    # - whitespace
    # - wsl
