run:
  timeout: 5m

issues:
  exclude-use-default: false

  exclude-rules:
    - linters:
        - golint
      text: "should have a package comment, unless it's in another file for this package"
    - linters:
        - golint
      text: "should not use dot imports"
    - linters:
        - golint
      text: "returns unexported type .* which can be annoying to use"
    - linters:
        - golint
      text: "error strings should not be capitalized or end with punctuation or a newline"

linters-settings:
  golint:
    min-confidence: 0
  govet:
    enable-all: true
    disable:
      - shadow
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - Print
          - Printf
          - Println
          - Debug
          - Debugf
          - Info
          - Infof
          - Warn
          - Warnf
          - Error
          - Errorf
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - commentFormatting
      - octalLiteral
      - unnamedResult
      - unnecessaryDefer
      - importShadow
      - emptyStringTest
      - hugeParam
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    # - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    - exportloopref
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    - gofmt
    - goimports
    - golint
    # - gomnd
    # - goprintffuncname
    # - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    - nakedret
    # - nestif
    - nolintlint
    # - prealloc
    - rowserrcheck
    # - scopelint
    # - staticcheck
    # - structcheck
    # - stylecheck
    # - testpackage
    # - typecheck
    - unconvert
    - unparam
    # - unused
    # - varcheck
    # - whitespace
    # - wsl
