- id: kube-linter
  name: KubeLinter
  description: This hook installs (using Go) and runs the KubeLinter utility to lint Helm charts and Kubernetes YAML files.
  entry: kube-linter lint 
  language: golang
  types: [yaml]

- id: kube-linter-system
  name: KubeLinter System
  description: This hook runs the KubeLinter utility that exists already on the system to lint Helm charts and Kubernetes YAML files.
  entry: kube-linter lint 
  language: system
  types: [yaml]

- id: kube-linter-docker
  name: KubeLinter Docker
  description: This hook runs kube-linter using the project's official docker image
  language: docker_image
  types: [yaml]
  entry: stackrox/kube-linter:v0.6.4 lint 
