- id: kube-linter
  name: Kube-Linter
  description: This hook installs (using Go) and runs the Kube-Linter utility to lint Helm charts and Kubernetes Yaml files.
  entry: kube-linter
  language: golang
  types: [yaml]

- id: kube-linter-system
  name: Kube-Linter-System
  description: This hook runs the Kube-Linter utility that exists already on the system to lint Helm charts and Kubernetes Yaml files.
  entry: kube-linter
  language: system
  types: [yaml]

- id: kube-linter-docker
  name: Kube-Linter-Docker
  description: This hook runs kube-linter using the projects official docker image
  language: docker_image
  types: [yaml]
  entry: stackrox/kube-linter:latest
