// Code generated by kube-linter template codegen. DO NOT EDIT.
//go:build !templatecodegen
// +build !templatecodegen

package params

import (
	"golang.stackrox.io/kube-linter/pkg/check"
	"golang.stackrox.io/kube-linter/pkg/templates/util"
)

var (
	// Use some imports in case they don't get used otherwise.
	_ = util.MustParseParameterDesc

	rulesParamDesc = util.MustParseParameterDesc(`{
	"Name": "rules",
	"Type": "array",
	"Description": "",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "string",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "Rules",
	"XXXIsPointer": false
}
`)

	excludeRulesParamDesc = util.MustParseParameterDesc(`{
	"Name": "excludeRules",
	"Type": "array",
	"Description": "",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "string",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "ExcludeRules",
	"XXXIsPointer": false
}
`)

	minSeverityParamDesc = util.MustParseParameterDesc(`{
	"Name": "minSeverity",
	"Type": "string",
	"Description": "",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "MinSeverity",
	"XXXIsPointer": false
}
`)

	suppressionsFileParamDesc = util.MustParseParameterDesc(`{
	"Name": "suppressionsFile",
	"Type": "string",
	"Description": "",
	"Examples": null,
	"Enum": null,
	"SubParameters": null,
	"ArrayElemType": "",
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "SuppressionsFile",
	"XXXIsPointer": false
}
`)

	ParamDescs = []check.ParameterDesc{
		rulesParamDesc,
		excludeRulesParamDesc,
		minSeverityParamDesc,
		suppressionsFileParamDesc,
	}
)

func (p *Params) Validate() error {
	return nil
}

// ParseAndValidate instantiates a Params object out of the passed map[string]interface{},
// validates it, and returns it.
// The return type is interface{} to satisfy the type in the Template struct.
func ParseAndValidate(m map[string]interface{}) (interface{}, error) {
	var p Params
	if err := util.DecodeMapStructure(m, &p); err != nil {
		return nil, err
	}
	if err := p.Validate(); err != nil {
		return nil, err
	}
	return p, nil
}

// WrapInstantiateFunc is a convenience wrapper that wraps an untyped instantiate function
// into a typed one.
func WrapInstantiateFunc(f func(p Params) (check.Func, error)) func(interface{}) (check.Func, error) {
	return func(paramsInt interface{}) (check.Func, error) {
		return f(paramsInt.(Params))
	}
}
