package flagutil

import (
	"fmt"
	"strings"

	"github.com/spf13/pflag"

	"github.com/pkg/errors"
	"golang.stackrox.io/kube-linter/internal/set"
	"golang.stackrox.io/kube-linter/internal/utils"
)

// EnumValue allows setting a list of values.
type EnumValue struct {
	flagDescription string
	allowedValues   set.FrozenStringSet

	currentValue string
}

// String implements pflag.Value.
// It is the preferred method of retrieving the set value for the enum.
func (e *EnumValue) String() string {
	return e.currentValue
}

// Set implements pflag.Value.
func (e *EnumValue) Set(input string) error {
	if !e.allowedValues.Contains(input) {
		return errors.Errorf("%q is not a valid option (valid options are: %v)", input, e.getAllowedValuesString())
	}
	e.currentValue = input
	return nil
}

// Type implements pflag.Value.
func (e *EnumValue) Type() string {
	return "string"
}

// Check that EnumValue implements pflag.Value interface.
var _ pflag.Value = (*EnumValue)(nil)

// Usage returns a string that can be used as help text for this flag.
// It will include the flag type and the list of allowed values.
func (e *EnumValue) Usage() string {
	return fmt.Sprintf("%s. Allowed values: %v.", e.flagDescription, e.getAllowedValuesString())
}

func (e *EnumValue) getAllowedValuesString() string {
	sorted := e.allowedValues.AsSortedSlice(func(i, j string) bool {
		return i < j
	})
	return strings.Join(sorted, ", ")
}

// NewEnumValueFactory returns a factory that can generate enum flag values with the given flag type
// and allowedValues. Concrete flag values are generated by calling the factory with a particular defaultValue.
func NewEnumValueFactory(flagDescription string, allowedValues []string) func(defaultValue string) *EnumValue {
	allowedValuesSet := set.NewFrozenStringSet(allowedValues...)
	return func(defaultValue string) *EnumValue {
		partialValue := &EnumValue{flagDescription: flagDescription, allowedValues: allowedValuesSet}
		utils.Must(partialValue.Set(defaultValue))
		return partialValue
	}
}
