// Code generated by kube-linter template codegen. DO NOT EDIT.
// +build !templatecodegen

package params

import (
	"github.com/pkg/errors"
	"golang.stackrox.io/kube-linter/internal/check"
	"golang.stackrox.io/kube-linter/internal/templates/util"
)

var (
	// Use this in case it doesn't get used otherwise.
	_ = util.MustParseParameterDesc


	nameParamDesc = util.MustParseParameterDesc(`{
	"Name": "name",
	"Type": "string",
	"Description": "The name of the environment variable.",
	"Examples": null,
	"SubParameters": null,
	"Required": true,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "Name"
}
`)
	valueParamDesc = util.MustParseParameterDesc(`{
	"Name": "value",
	"Type": "string",
	"Description": "The value of the environment variable.",
	"Examples": null,
	"SubParameters": null,
	"Required": false,
	"NoRegex": false,
	"NotNegatable": false,
	"XXXStructFieldName": "Value"
}
`)

	ParamDescs = []check.ParameterDesc{
		nameParamDesc,
		valueParamDesc,
	}
)

func (p *Params) Validate() error {
	var missingRequiredParams []string
	if p.Name == "" {
		missingRequiredParams = append(missingRequiredParams, "name")
	}
	if len(missingRequiredParams) > 0 {
		return errors.Errorf("required params %v not found", missingRequiredParams)
    }
	return nil
}

// ParseAndValidate instantiates a Params object out of the passed map[string]interface{},
// validates it, and returns it.
// The return type is interface{} to satisfy the type in the Template struct.
func ParseAndValidate(m map[string]interface{}) (interface{}, error) {
	var p Params
	if err := util.DecodeMapStructure(m, &p); err != nil {
		return nil, err
	}
	if err := p.Validate(); err != nil {
		return nil, err
	}
	return p, nil
}

// WrapInstantiateFunc is a convenience wrapper that wraps an untyped instantiate function
// into a typed one.
func WrapInstantiateFunc(f func(p Params) (check.Func, error)) func (interface{}) (check.Func, error) {
	return func(paramsInt interface{}) (check.Func, error) {
		return f(paramsInt.(Params))
	}
}
